/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AI Graph Chat API
 * REST API для приложения AI Graph Chat
 * OpenAPI spec version: 1.0.0
 */

export interface Message {
  /** Уникальный идентификатор сообщения */
  id: string;
  /** ID чата */
  chat_id: string;
  /** ID отправителя */
  user_id: string;
  /**
   * Содержимое сообщения
   * @maxLength 10000
   */
  content: string;
  /** Дата создания */
  created_at: string;
}
