/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AI Graph Chat API
 * REST API для приложения AI Graph Chat
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateChatRequest {
  /**
   * Новое название чата
   * @maxLength 255
   */
  title: string;
}
