/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AI Graph Chat API
 * REST API для приложения AI Graph Chat
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  /** Уникальный идентификатор пользователя */
  id: string;
  /** Google ID пользователя */
  google_id: string;
  /** Email пользователя */
  email: string;
  /** Имя пользователя */
  name: string;
  /** OpenRouter API ключ */
  openrouter_api_key?: string;
}
