/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AI Graph Chat API
 * REST API для приложения AI Graph Chat
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error
} from './dto/schemas-objects-dto-error';
import type {
  GoogleAuthRequest
} from './dto/schemas-objects-dto-google-auth-request';
import type {
  UpdateUserRequest
} from './dto/schemas-objects-dto-update-user-request';
import type {
  CreateChatRequest
} from './dto/schemas-objects-dto-create-chat-request';
import type {
  UpdateChatRequest
} from './dto/schemas-objects-dto-update-chat-request';
import type {
  GetChatsChatIdMessagesParams
} from './dto';
import type {
  SendMessageRequest
} from './dto/schemas-objects-dto-send-message-request';

import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  GoogleAuthResponse
} from './dto/schemas-objects-dto-google-auth-response';
import type {
  User
} from './dto/schemas-objects-dto-user';
import type {
  ChatsResponse
} from './dto/schemas-objects-dto-chats-response';
import type {
  Chat
} from './dto/schemas-objects-dto-chat';
import type {
  MessagesResponse
} from './dto/schemas-objects-dto-messages-response';
import type {
  Message
} from './dto/schemas-objects-dto-message';

import { customInstance } from './axiosClient';
/**
 * Обмен authorization code на JWT токен
 * @summary Аутентификация через Google OAuth
 */
export const postAuthGoogle = (
    googleAuthRequest: GoogleAuthRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GoogleAuthResponse>(
      {url: `/auth/google`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: googleAuthRequest, signal
    },
      );
    }
  


export const getPostAuthGoogleMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthGoogle>>, TError,{data: GoogleAuthRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthGoogle>>, TError,{data: GoogleAuthRequest}, TContext> => {

const mutationKey = ['postAuthGoogle'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthGoogle>>, {data: GoogleAuthRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthGoogle(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthGoogleMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthGoogle>>>
    export type PostAuthGoogleMutationBody = GoogleAuthRequest
    export type PostAuthGoogleMutationError = Error

    /**
 * @summary Аутентификация через Google OAuth
 */
export const usePostAuthGoogle = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthGoogle>>, TError,{data: GoogleAuthRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthGoogle>>,
        TError,
        {data: GoogleAuthRequest},
        TContext
      > => {

      const mutationOptions = getPostAuthGoogleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Возвращает информацию о текущем аутентифицированном пользователе
 * @summary Получить профиль пользователя
 */
export const getUser = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<User>(
      {url: `/user`, method: 'GET', signal
    },
      );
    }
  



export const getGetUserQueryKey = () => {
    return [
    `/user`
    ] as const;
    }

    
export const getGetUserQueryOptions = <TData = Awaited<ReturnType<typeof getUser>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({ signal }) => getUser(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type GetUserQueryError = Error


export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = Error>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить профиль пользователя
 */

export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Обновляет информацию о пользователе (OpenRouter API ключ)
 * @summary Обновить профиль пользователя
 */
export const patchUser = (
    updateUserRequest: UpdateUserRequest,
 ) => {
      
      
      return customInstance<User>(
      {url: `/user`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUserRequest
    },
      );
    }
  


export const getPatchUserMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchUser>>, TError,{data: UpdateUserRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchUser>>, TError,{data: UpdateUserRequest}, TContext> => {

const mutationKey = ['patchUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchUser>>, {data: UpdateUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchUser(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchUserMutationResult = NonNullable<Awaited<ReturnType<typeof patchUser>>>
    export type PatchUserMutationBody = UpdateUserRequest
    export type PatchUserMutationError = Error

    /**
 * @summary Обновить профиль пользователя
 */
export const usePatchUser = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchUser>>, TError,{data: UpdateUserRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchUser>>,
        TError,
        {data: UpdateUserRequest},
        TContext
      > => {

      const mutationOptions = getPatchUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Возвращает все чаты аутентифицированного пользователя
 * @summary Получить список чатов пользователя
 */
export const getChats = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ChatsResponse>(
      {url: `/chats`, method: 'GET', signal
    },
      );
    }
  



export const getGetChatsQueryKey = () => {
    return [
    `/chats`
    ] as const;
    }

    
export const getGetChatsQueryOptions = <TData = Awaited<ReturnType<typeof getChats>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChats>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChats>>> = ({ signal }) => getChats(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChatsQueryResult = NonNullable<Awaited<ReturnType<typeof getChats>>>
export type GetChatsQueryError = Error


export function useGetChats<TData = Awaited<ReturnType<typeof getChats>>, TError = Error>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChats>>,
          TError,
          Awaited<ReturnType<typeof getChats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChats<TData = Awaited<ReturnType<typeof getChats>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChats>>,
          TError,
          Awaited<ReturnType<typeof getChats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChats<TData = Awaited<ReturnType<typeof getChats>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChats>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить список чатов пользователя
 */

export function useGetChats<TData = Awaited<ReturnType<typeof getChats>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChats>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Создает новый чат для аутентифицированного пользователя
 * @summary Создать новый чат
 */
export const postChats = (
    createChatRequest?: CreateChatRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Chat>(
      {url: `/chats`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createChatRequest, signal
    },
      );
    }
  


export const getPostChatsMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChats>>, TError,{data: CreateChatRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postChats>>, TError,{data: CreateChatRequest}, TContext> => {

const mutationKey = ['postChats'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postChats>>, {data: CreateChatRequest}> = (props) => {
          const {data} = props ?? {};

          return  postChats(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostChatsMutationResult = NonNullable<Awaited<ReturnType<typeof postChats>>>
    export type PostChatsMutationBody = CreateChatRequest
    export type PostChatsMutationError = Error

    /**
 * @summary Создать новый чат
 */
export const usePostChats = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChats>>, TError,{data: CreateChatRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postChats>>,
        TError,
        {data: CreateChatRequest},
        TContext
      > => {

      const mutationOptions = getPostChatsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Обновляет название чата
 * @summary Переименовать чат
 */
export const patchChatsChatId = (
    chatId: string,
    updateChatRequest: UpdateChatRequest,
 ) => {
      
      
      return customInstance<Chat>(
      {url: `/chats/${chatId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateChatRequest
    },
      );
    }
  


export const getPatchChatsChatIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchChatsChatId>>, TError,{chatId: string;data: UpdateChatRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchChatsChatId>>, TError,{chatId: string;data: UpdateChatRequest}, TContext> => {

const mutationKey = ['patchChatsChatId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchChatsChatId>>, {chatId: string;data: UpdateChatRequest}> = (props) => {
          const {chatId,data} = props ?? {};

          return  patchChatsChatId(chatId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchChatsChatIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchChatsChatId>>>
    export type PatchChatsChatIdMutationBody = UpdateChatRequest
    export type PatchChatsChatIdMutationError = Error

    /**
 * @summary Переименовать чат
 */
export const usePatchChatsChatId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchChatsChatId>>, TError,{chatId: string;data: UpdateChatRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchChatsChatId>>,
        TError,
        {chatId: string;data: UpdateChatRequest},
        TContext
      > => {

      const mutationOptions = getPatchChatsChatIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Удаляет чат и все связанные сообщения
 * @summary Удалить чат
 */
export const deleteChatsChatId = (
    chatId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/chats/${chatId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteChatsChatIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChatsChatId>>, TError,{chatId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteChatsChatId>>, TError,{chatId: string}, TContext> => {

const mutationKey = ['deleteChatsChatId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteChatsChatId>>, {chatId: string}> = (props) => {
          const {chatId} = props ?? {};

          return  deleteChatsChatId(chatId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteChatsChatIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChatsChatId>>>
    
    export type DeleteChatsChatIdMutationError = Error

    /**
 * @summary Удалить чат
 */
export const useDeleteChatsChatId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChatsChatId>>, TError,{chatId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteChatsChatId>>,
        TError,
        {chatId: string},
        TContext
      > => {

      const mutationOptions = getDeleteChatsChatIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Возвращает предыдущие сообщения при прокрутке вверх
 * @summary Получить сообщения чата с пагинацией
 */
export const getChatsChatIdMessages = (
    chatId: string,
    params?: GetChatsChatIdMessagesParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MessagesResponse>(
      {url: `/chats/${chatId}/messages`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetChatsChatIdMessagesQueryKey = (chatId?: string,
    params?: GetChatsChatIdMessagesParams,) => {
    return [
    `/chats/${chatId}/messages`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetChatsChatIdMessagesQueryOptions = <TData = Awaited<ReturnType<typeof getChatsChatIdMessages>>, TError = Error>(chatId: string,
    params?: GetChatsChatIdMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatsChatIdMessages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChatsChatIdMessagesQueryKey(chatId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChatsChatIdMessages>>> = ({ signal }) => getChatsChatIdMessages(chatId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(chatId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChatsChatIdMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChatsChatIdMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof getChatsChatIdMessages>>>
export type GetChatsChatIdMessagesQueryError = Error


export function useGetChatsChatIdMessages<TData = Awaited<ReturnType<typeof getChatsChatIdMessages>>, TError = Error>(
 chatId: string,
    params: undefined |  GetChatsChatIdMessagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatsChatIdMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatsChatIdMessages>>,
          TError,
          Awaited<ReturnType<typeof getChatsChatIdMessages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChatsChatIdMessages<TData = Awaited<ReturnType<typeof getChatsChatIdMessages>>, TError = Error>(
 chatId: string,
    params?: GetChatsChatIdMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatsChatIdMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatsChatIdMessages>>,
          TError,
          Awaited<ReturnType<typeof getChatsChatIdMessages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChatsChatIdMessages<TData = Awaited<ReturnType<typeof getChatsChatIdMessages>>, TError = Error>(
 chatId: string,
    params?: GetChatsChatIdMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatsChatIdMessages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить сообщения чата с пагинацией
 */

export function useGetChatsChatIdMessages<TData = Awaited<ReturnType<typeof getChatsChatIdMessages>>, TError = Error>(
 chatId: string,
    params?: GetChatsChatIdMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatsChatIdMessages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChatsChatIdMessagesQueryOptions(chatId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Отправляет новое сообщение в чат
 * @summary Отправить сообщение
 */
export const postChatsChatIdMessages = (
    chatId: string,
    sendMessageRequest: SendMessageRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Message>(
      {url: `/chats/${chatId}/messages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendMessageRequest, signal
    },
      );
    }
  


export const getPostChatsChatIdMessagesMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChatsChatIdMessages>>, TError,{chatId: string;data: SendMessageRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postChatsChatIdMessages>>, TError,{chatId: string;data: SendMessageRequest}, TContext> => {

const mutationKey = ['postChatsChatIdMessages'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postChatsChatIdMessages>>, {chatId: string;data: SendMessageRequest}> = (props) => {
          const {chatId,data} = props ?? {};

          return  postChatsChatIdMessages(chatId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostChatsChatIdMessagesMutationResult = NonNullable<Awaited<ReturnType<typeof postChatsChatIdMessages>>>
    export type PostChatsChatIdMessagesMutationBody = SendMessageRequest
    export type PostChatsChatIdMessagesMutationError = Error

    /**
 * @summary Отправить сообщение
 */
export const usePostChatsChatIdMessages = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChatsChatIdMessages>>, TError,{chatId: string;data: SendMessageRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postChatsChatIdMessages>>,
        TError,
        {chatId: string;data: SendMessageRequest},
        TContext
      > => {

      const mutationOptions = getPostChatsChatIdMessagesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }


export const getPostAuthGoogleResponseMock = (overrideResponse: Partial< GoogleAuthResponse > = {}): GoogleAuthResponse => ({token: faker.string.alpha({length: {min: 10, max: 20}}), user: {id: faker.string.uuid(), google_id: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.internet.email(), name: faker.string.alpha({length: {min: 10, max: 20}}), openrouter_api_key: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, ...overrideResponse})

export const getGetUserResponseMock = (overrideResponse: Partial< User > = {}): User => ({id: faker.string.uuid(), google_id: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.internet.email(), name: faker.string.alpha({length: {min: 10, max: 20}}), openrouter_api_key: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getPatchUserResponseMock = (overrideResponse: Partial< User > = {}): User => ({id: faker.string.uuid(), google_id: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.internet.email(), name: faker.string.alpha({length: {min: 10, max: 20}}), openrouter_api_key: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getGetChatsResponseMock = (): ChatsResponse => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), user_id: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 255}}), created_at: `${faker.date.past().toISOString().split('.')[0]}Z`, updated_at: `${faker.date.past().toISOString().split('.')[0]}Z`, is_loading: faker.datatype.boolean()})))

export const getPostChatsResponseMock = (overrideResponse: Partial< Chat > = {}): Chat => ({id: faker.string.uuid(), user_id: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 255}}), created_at: `${faker.date.past().toISOString().split('.')[0]}Z`, updated_at: `${faker.date.past().toISOString().split('.')[0]}Z`, is_loading: faker.datatype.boolean(), ...overrideResponse})

export const getPatchChatsChatIdResponseMock = (overrideResponse: Partial< Chat > = {}): Chat => ({id: faker.string.uuid(), user_id: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 255}}), created_at: `${faker.date.past().toISOString().split('.')[0]}Z`, updated_at: `${faker.date.past().toISOString().split('.')[0]}Z`, is_loading: faker.datatype.boolean(), ...overrideResponse})

export const getGetChatsChatIdMessagesResponseMock = (): MessagesResponse => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), chat_id: faker.string.uuid(), user_id: faker.string.uuid(), content: faker.string.alpha({length: {min: 10, max: 10000}}), created_at: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getPostChatsChatIdMessagesResponseMock = (overrideResponse: Partial< Message > = {}): Message => ({id: faker.string.uuid(), chat_id: faker.string.uuid(), user_id: faker.string.uuid(), content: faker.string.alpha({length: {min: 10, max: 10000}}), created_at: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})


export const getPostAuthGoogleMockHandler = (overrideResponse?: GoogleAuthResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<GoogleAuthResponse> | GoogleAuthResponse), options?: RequestHandlerOptions) => {
  return http.post('*/auth/google', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostAuthGoogleResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetUserMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.get('*/user', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getPatchUserMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.patch('*/user', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPatchUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetChatsMockHandler = (overrideResponse?: ChatsResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ChatsResponse> | ChatsResponse), options?: RequestHandlerOptions) => {
  return http.get('*/chats', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetChatsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getPostChatsMockHandler = (overrideResponse?: Chat | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Chat> | Chat), options?: RequestHandlerOptions) => {
  return http.post('*/chats', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostChatsResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getPatchChatsChatIdMockHandler = (overrideResponse?: Chat | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Chat> | Chat), options?: RequestHandlerOptions) => {
  return http.patch('*/chats/:chatId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPatchChatsChatIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteChatsChatIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/chats/:chatId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}

export const getGetChatsChatIdMessagesMockHandler = (overrideResponse?: MessagesResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MessagesResponse> | MessagesResponse), options?: RequestHandlerOptions) => {
  return http.get('*/chats/:chatId/messages', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetChatsChatIdMessagesResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getPostChatsChatIdMessagesMockHandler = (overrideResponse?: Message | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Message> | Message), options?: RequestHandlerOptions) => {
  return http.post('*/chats/:chatId/messages', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostChatsChatIdMessagesResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getAIGraphChatAPIMock = () => [
  getPostAuthGoogleMockHandler(),
  getGetUserMockHandler(),
  getPatchUserMockHandler(),
  getGetChatsMockHandler(),
  getPostChatsMockHandler(),
  getPatchChatsChatIdMockHandler(),
  getDeleteChatsChatIdMockHandler(),
  getGetChatsChatIdMessagesMockHandler(),
  getPostChatsChatIdMessagesMockHandler()
]
