/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AI Graph Chat API
 * REST API для приложения AI Graph Chat
 * OpenAPI spec version: 1.0.0
 */

export type GetChatsChatIdMessagesParams = {
/**
 * ID сообщения, перед которым загружать
 */
before?: string;
/**
 * Количество сообщений
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
