/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AI Graph Chat API
 * REST API для приложения AI Graph Chat
 * OpenAPI spec version: 1.0.0
 */

export interface Chat {
  /** Уникальный идентификатор чата */
  id: string;
  /** ID владельца чата */
  user_id: string;
  /**
   * Название чата
   * @maxLength 255
   */
  title: string;
  /** Дата создания */
  created_at: string;
  /** Дата последнего обновления */
  updated_at: string;
  /** Статус загрузки (ИИ пишет) */
  is_loading: boolean;
}
