/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AI Graph Chat API
 * REST API для приложения AI Graph Chat
 * OpenAPI spec version: 1.0.0
 */
import type { User } from '../schemas-objects-dto-user/user';

export interface GoogleAuthResponse {
  /** JWT токен */
  token: string;
  user: User;
}
